### ISSUE TITLE
Update vedirect-interface to use new libevent 

### ISSUE THREAD

**Issue by dpackham** [jhofstee/meta-bin-deb#2]
Trying to install venus code on a new raspberry pi install on a pi3b+

I get the following errors. I cant run jesse on the pi3b+ as it will not boot due to missing firmware

root@raspberrypi:~# apt install vedirect-interface
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
vedirect-interface : Depends: glibc-deb but it is not installable
Depends: libevent-2.0-5 (>= 2.0.21-stable-2+deb8u1) but it is not installable
Depends: libevent-pthreads-2.0-5 (>= 2.0.21-stable-2+deb8u1) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by jhofstee** [comment]
ok, part 1 is done, the venus-bot now also generates the meta data for buster, see https://github.com/venus-bot/meta-bin-deb-generated/tree/master/meta-generated.

**Comment by ersingencturk** [comment]
so how is this meta data useful to solve this ?

**Comment by juwei80** [comment]
I have the same problem when trying to upgrade vedirect-interface from the installed 3.45-r0 to the current 3.50-1.0 on raspbian buster:
```
# apt upgrade vedirect-interface
Paketlisten werden gelesen... Fertig
Abhängigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
Paketaktualisierung (Upgrade) wird berechnet... Fertig
Einige Pakete konnten nicht installiert werden. Das kann bedeuten, dass
Sie eine unmögliche Situation angefordert haben oder, wenn Sie die
Unstable-Distribution verwenden, dass einige erforderliche Pakete noch
nicht erstellt wurden oder Incoming noch nicht verlassen haben.
Die folgenden Informationen helfen Ihnen vielleicht, die Situation zu lösen:

Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 vedirect-interface : Hängt ab von: glibc-deb ist aber nicht installierbar
E: Beschädigte Pakete
```

The depends got changed and glibc-deb is not part of the distro:
```
# apt-cache show vedirect-interface
Package: vedirect-interface
Version: 3.50-1.0
Priority: optional
Section: base
Filename: pool/main/v/vedirect-interface/vedirect-interface_3.50-1.0_armhf.deb
Size: 48382
SHA256: 8491e60879558bb3eb9e001614d991705f0652c022bcc912426bdcca51ad1148
SHA1: ed79bc7bea789987d6d4bc09ce49a9fdd7264aa5
MD5sum: 6e203e66fa8b0563c8cdb151cf2adce1
Description: vedirect-interface version 3.50-1
 ve.direct daemon
Description-md5: 99eb59774e043211fa553630fb5373c1
Maintainer: OE-Core Developers <openembedded-core@lists.openembedded.org>
Architecture: armhf
OE: vedirect-interface
PackageArch: arm1176jzfshf-vfp
Depends: bash, daemontools-run, glibc-deb, libc6 (>= 2.19-18+deb8u10), libdbus-1-3 (>= 1.8.22-0+deb8u3), libevent-2.0-5 (>= 2.0.21-stable-2+deb8u1), libevent-pthreads-2.0-5 (>= 2.0.21-stable-2+deb8u1)

Package: vedirect-interface
Status: install ok installed
Priority: optional
Section: base
Maintainer: OE-Core Developers <openembedded-core@lists.openembedded.org>
Architecture: armhf
Version: 3.45-r0.0
Depends: bash, daemontools-run, libc6 (>= 2.19-18+deb8u10), libdbus-1-3 (>= 1.8.22-0+deb8u2), libevent-2.0-5 (>= 2.0.21-stable-2+deb8u1), libevent-pthreads-2.0-5 (>= 2.0.21-stable-2+deb8u1)
Description: vedirect-interface version 3.45-r0
 ve.direct daemon
Description-md5: f78064ae106160a271468bff49db4eda
OE: vedirect-interface
PackageArch: arm1176jzfshf-vfp
```

3.45 worked pretty well... So i will keep it until a fixed version is available in the apt repo (https://updates.victronenergy.com/feeds/venus/release/packages/raspbian-jessie)

**Comment by jhofstee** [comment]
I included it in the 2.70 build, https://github.com/victronenergy/venus/commit/bc300d3cc35c7a8438a430b4a5425922167b5c9c.
Attached as binary for the rpi, v2.62 will be released before, so it might not yet be in the regular feeds. Untested btw.

[vedirect-interface_3.57-1.0_armhf.deb.gz](https://github.com/jhofstee/meta-bin-deb/files/5900893/vedirect-interface_3.57-1.0_armhf.deb.gz)

**Comment by jhofstee** [comment]
> so how is this meta data useful to solve this ?

Because the meta data contains the version of libevent to build against, and specify the dependencies in the deb file.

**Comment by jhofstee** [comment]
> The depends got changed and glibc-deb is not part of the distro:

Right, I thought this issue was about needing a newer libevent. While that is an issue for some Debian versions, the glibc-deb dependency is the actual problem for this issue. I will have a look where that is coming from if I have time. That shouldn't be there..

**Comment by Dukat-Gul** [comment]
It seems the general Debian/Raspbian repos have been removed.
https://updates.victronenergy.com/feeds/venus/release/packages/raspbian-jessie is 404 Not Found
https://updates.victronenergy.com/feeds/venus/release/packages/debian-jessie is also 404
in the past buster was available for both - seems to have all gone.
The guide
https://github.com/victronenergy/venus/wiki/install-venus-packages-on-Debian
is obviously no longer up to date.


> I had a look why the package index is not created correctly, [victronenergy/openembedded-core@482f234](https://github.com/victronenergy/openembedded-core/commit/482f234e88e6ea46bfe874f997b914bce22deae9) should fix that. It should be fixed in Venus v2.70~13.

**Comment by Dukat-Gul** [comment]
Seems buster for raspbian and debian have been put back in June 2022

https://updates.victronenergy.com/feeds/venus/candidate/packages/

**Comment by jhofstee** [comment]
Yes they were lost by accident, but they are back again.
